### ISSUE TITLE
Hey! Just thought I'd share this with you!

### ISSUE THREAD

**Issue by bashleigh** [davorg/planetbalham#1]
Not sure what this repo is for but it's apparently the most popular repo in the UK 😂 https://profile.codersrank.io/year-in-review-2020/country/uk/

**Comment by davorg** [comment]
Wow. Thanks for letting me know. I guess they really need a way to filter out commits that were made automatically by GitHub Actions :-)

**Comment by bashleigh** [comment]
haha defo :p What does the repo do? Is it like an info dashboard? Could see weather update etc so was curious :)

**Comment by davorg** [comment]
It builds this site - https://balham.theplanetarium.org/ - which aggregates various web feeds about Balham. But it's been going for a long time and most of the feeds I originally used have died. Pretty much the only really active one is the BBC weather forecast for Balham - which is why you're seen a lot of that data.

I should revisit it and add some more interesting feeds.

**Comment by bashleigh** [comment]
Oh right! That's pretty cool actually!
